### ISSUE TITLE
`get_pns` and `read_pns` functions are not working

### ISSUE THREAD

**Issue by diegogaldinof** [Gabriel-Assuncao/PNSIBGE#1]
Hello, Gabriel!

I'm trying to download and use PNS 2019 data in R through the `PNSIBGE` package but I'm getting errors with the `get_pns` and `read_pns` functions. When I run `get_pns`, R downloads the zip file and saves it normally. However, I get the error "substr(X1, 1, 1) : invalid multibyte string, element 2".

``` r
library(PNSIBGE)
#> Warning: package 'PNSIBGE' was built under R version 4.1.3
dataset <- get_pns(2019, selected = TRUE)
#> Error in substr(X1, 1, 1): invalid multibyte string, element 2
```

<sup>Created on 2022-04-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The same error appears with the `read_pns` function. Here is an example using the same shared in the documentation:
``` r
input_path <- pns_example(path="input_example.txt")
data_path <- pns_example(path="exampledata.txt")
pns.df <- read_pns(microdata=data_path, input_txt=input_path, vars=c("J007","J009"))
#> Error in substr(X1, 1, 1): invalid multibyte string, element 2
```

<sup>Created on 2022-04-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Gabriel-Assuncao** [comment]
Hello Diego. How are you doing?

This error is occurring because when we updated the PNSIBGE package on 11/30/2021, and kept it in the 03/24/2022 update, we decided to do a complete code scan evaluating all the functions that are being used, including those that are from other packages and in this scenario we verified that one of the functions we used to read the microdata would become obsolete/deprecated, so we decided to change it to the active version, and this function is part of the readr package, so basically what needs to be done to correct this problem is to update the version of the package readr using the command install.packages("readr") and after carrying out this procedure, the indicated error will be corrected, being possible to obtain the microdata normally.

We take the opportunity to indicate the constant verification of the version of the packages that are being used, and for the specific case it is necessary that the installed version of the R software must be equal to or greater than '3.1', the version of the PNSIBGE package must be equal to or greater than ' 0.1.6' (version 0.1.7 already exists) and the readr package version must be equal to or greater than '2.1.1'.

We hope that the information above is sufficient to resolve the issues presented, however, if there is still any pending issues, we kindly ask you to contact the customer service channel pacotesipd@ibge.gov.br. So we will close this issue and anything will be available through the channel indicated above.
